name: Configure Repository Settings

on:
  schedule:
    # Run the workflow every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  configure_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.REPO_ADMIN_ACCESS_TOKEN }}" | gh auth login --with-token

    - name: Configure repository settings
      run: |
        gh api "repos/${{ github.repository_owner }}/${{ github.event.repository.name }}" \
          --method PATCH \
          --silent \
          --field allow_auto_merge=true \
          --field allow_merge_commit=false \
          --field allow_rebase_merge=false \
          --field allow_squash_merge=true \
          --field delete_branch_on_merge=true \
          --field has_issues=true \
          --field has_projects=false \
          --field has_wiki=false \
          --field squash_merge_commit_message=PR_BODY \
          --field squash_merge_commit_title=PR_TITLE
