name: repo backup
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  repo-backup:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # retrieve all history

    - name: Create ZIP bundle
      run: |
        ZIP_FILE="${{ github.repository }}-$(date '+%Y-%m-%d').zip"
        zip -rq "${ZIP_FILE}" .
        mkdir -p backups/${{ github.repository }}
        mv "${ZIP_FILE}" backups/${{ github.repository }}

    - name: Send ZIP to Backup Bucket
      run: |
        curl -X POST "${{ secrets.GITHUB_BACKUP_URL }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @backups/${{ github.repository }}/${ZIP_FILE}
